### PR TITLE
ci: Add initial CI using GitHub Actions.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This is just a quick initial CI that I use elsewhere in case you're interested in having CI on this repo ...

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
Ah, this will fail due to clippy warnings from `--all-targets` ... I'll fix something up there if you're interested, so just let me know.

**Review by frewsxcv — APPROVED** [review]
thank you so much!

**Comment by frewsxcv** [comment]
FYI https://github.com/frewsxcv/earcutr/actions/runs/6569696376

**Comment by waywardmonkeys** [comment]
Submitted fix in #8.

**Pull request merged**
